### ISSUE TITLE
Consistent app/ structure

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/pwa-starter#20]
With purposely I moved the main app layout to its own app for consistency, so `/client/index.js` is as barebones as possible, and apps are all in the same place.

thoughts @staydecent  ?

purposely client/index:
https://github.com/inputlogic/purposely/blob/develop/frontend/client/index.js

purposely apps/app
https://github.com/inputlogic/purposely/tree/develop/frontend/client/apps/app

**Comment by staydecent** [comment]
Hmm, I think keeping the top-level component outside the app folder makes sense. Aren't all components going to be a child of `<App />`?

That's why it's in the root, no?

**Comment by staydecent** [comment]
It could make sense to follow React Native default structure, index.js and an App.js

https://github.com/inputlogic/neighbors-mobile

**Comment by staydecent** [comment]
Hmmm, but what defines an App? is an App jsut a component that renders a Router? I guess by that definition they could all live in the same folder?

**Comment by adriaanwm** [comment]
That's my understanding of an app. in an app folder there's a `routes.js` file

**Comment by staydecent** [comment]
Cool, then I think you're right. 🚀

**Comment by staydecent** [comment]
Hmm the weird thing is how urlFor/allRoutes needs to assume a `apps/app`, and it still feels like this app is different as it's the root that gets mounted -- nothing else happens without this root.

I'm not sure if this change would make things clearer, or more hidden?
