### ISSUE TITLE
Native-like screen transitions

### ISSUE THREAD

**Issue by staydecent** [inputlogic/pwa-starter#23]

**Comment by adriaanwm** [comment]
Multiple app stacks. Could have 4 tabs at the bottom, then each of those could have an app stack. 

On iOS music, if you're on library tab, go into artists, go to for you tab, then go back to library tab, it's still on the artists page.

**Comment by staydecent** [comment]
I think this could be broken into two Components: BottomNavBar and NavStack.

NavStack would define stack of routes, and how each can be accessed:
```javascript
createNavStack(
  {
    Library: {
      route: '/library',
      component: Library
    },
    Artists: {
      route: '/library/artists',
      parent: 'Library',
      component: Artists
    },
    Artist: {
      route: '/library/artists/:id',
      parent: 'Artists',
      component: Artist
    },
  },
  {
    initialRoute: 'Library'
  }
)
```

We'd need to figure out where Router and the Stacks concepts overlap to reduce code/work. Then, any child/page/screen of a Stack would perhaps be wrapped with a `<StackProvider />` so when you render `Artist`, we know to use the previously defined stack to intercept back buttons.

**Comment by staydecent** [comment]
I wonder if the `parent` key is even necessary, or if it's safe/flexible enough to build hierarchy from the route segments.

**Comment by staydecent** [comment]
Interesting reference to see if we can enable material motion designs: https://marmelab.com/blog/2017/12/04/material-design-animations-react-router.html

**Comment by adriaanwm** [comment]
I don't think stacks need to be defined that rigidly, Often you could access the artist page from more than one page on the stack. With Learnly the idea of an app stack was just an array, and any link either had a push, pop, reset, or replace.

push: add the current route to the app stack [] => [{routeName: Whatever, url: ...}]
pop: remove from the app stack (used for back button) [{routeName: Whatever, url: ...}] => []
reset: replace the entire app stack (used for the tabs at the bottom) [{}, {}, {}] => []
replace: just replace the last entry in app stack (for example if you have a secondary like on purposely profile page) [{}, {routeName: a}] => [{}, {routeName: b}]

For multiple tabs, I would translate them to multiple app stacks, maybe the link could have a `tab` prop that would change the value of the current app stack... in state that might look like

```
{
   AppStacks: {
        library: [{}, {}],
        settings: [],
        messaging: [{}]
   }
}
```

**Comment by staydecent** [comment]
Likely relies on https://github.com/inputlogic/elements/issues/99
