### ISSUE TITLE
handle expired tokens and forbidden api calls by default

### ISSUE THREAD

**Issue by staydecent** [inputlogic/pwa-starter#48]
```javascript
const xhr = window.XMLHttpRequest
const nativeOpen = xhr.prototype.open

xhr.prototype.open = function () {
  this.addEventListener('load', function () {
    if (this.responseURL.indexOf(API_URL) === -1) return
    switch (this.status) {
      case 401:
        const err = this.responseText
        logout()
        showNotification({error: parseErrorDetail(err)})
        break

      case 402:
        Rollbar.error('User subscription is no longer valid! @TODO: this need to be handled.')
        break

      case 403:
        logout()
        break
    }
  })
  nativeOpen.apply(this, arguments)
}
```

**Comment by weslord** [comment]
Logging out the user on a 403 seems a little extreme; see https://github.com/inputlogic/deckster-html/pull/16#discussion_r326747239 for relevant case where that behaviour is already happening for some reason, with unwanted results.

**Comment by staydecent** [comment]
What's done in each case isn't going to be 100% standard across projects. To keep the base more friendly in terms of defaults, we could have a forbidden page, or redirect with notification.

**Comment by weslord** [comment]
Showing a notification for errors by default makes sense. Not a fan of the redirect - could cause confusion when working on a page that displays the results of multiple endpoints, or where you send a POST in-place, or are using some 3rd party API.
