### ISSUE TITLE
.eslintrc.js needs a .eslintrceslintrc.js

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/pwa-starter#74]
The `.eslintrc.js` file has inconsistent use of double and single quotes. One solution would be to add a eslinrc for the estlintrc... `eslintrceslintrc.js`

**Comment by staydecent** [comment]
Why does this matter? One of the new rules is to not care about single vs double quotes..

https://github.com/inputlogic/pwa-starter/blob/master/.eslintrc.js#L42

**Comment by staydecent** [comment]
Let me know if you want to discuss amending the quote rule. I figured it offers no real benefit, to enforce one over the other.

Sometimes it's nice to switch so you don't need to escape quotes:

```
alert('Say "Hello"');
alert("Say 'Hello'");
```

**Comment by weslord** [comment]
Personally I think we should enforce backticks (`) as the quote convention

**Comment by adriaanwm** [comment]
My left pinky doesn't have the endurance for that yet, can we have a few weeks of transition training first?
