### ISSUE TITLE
CSS Broken Sometimes

### ISSUE THREAD

**Issue by adriaanwm** [inputlogic/pwa-starter#89]
Sometimes css breaks on `npm start`, this has happened to both Cory and I. This wasn't too big a deal since we could just start again and eventually it works. 
Unfortunately it just happened on staging, so now I think it's something that needs fixing.

**Comment by adriaanwm** [comment]
This happened again, so I inspected CSS. It looks like for some reason the reset css is being assigned after our custom styling (so in inspect it was at the very top).

Maybe importing less into js is not resulting in reliable css order?

**Comment by staydecent** [comment]
Yeah the LESS bundling is pretty hacked in. We should look for a more official plugin for rollup. I miss brunches enforced ordering of assets :(

I'd like to move to parcel or another bundler that works with less configuration. But, I'll look for a quicker fix for now.

**Comment by staydecent** [comment]
Relevant issue: https://github.com/thgh/rollup-plugin-css-only/issues/16

**Comment by staydecent** [comment]
Currently fixed in this fork: https://github.com/staydecent/rollup-plugin-css-only

And waiting on PR to be upstreamed: https://github.com/thgh/rollup-plugin-css-only/pull/21

**Comment by staydecent** [comment]
man, getting this on every build on netlify...
